version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${name}
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_DB: management_service
    volumes:
      - /home/docker_images/postgres:/var/lib/postgresql/data
  test_db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${name}
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_DB: test_management_service
    volumes:
      - /home/docker_images/test_postgres:/var/lib/postgresql/data
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"     
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/home/docker_images/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 30 1 --loglevel warning --requirepass ${pass}
    volumes:
      - /home/docker_images/redis:/data
  rabbitmq_manage:
    image: rabbitmq:3.10.7-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${name}
      RABBITMQ_DEFAULT_PASS: ${pass}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648
    volumes:
      - /home/docker_images/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
  backend:
    build: .
    container_name: "backend"
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=cache
      - RABBITMQ_HOST=rabbitmq_manage
      - LOCALSTACK_HOST=localstack
    depends_on:
      - localstack
      - cache
      - rabbitmq_manage

