"""Initial tables

Revision ID: 0ba29cda6a9f
Revises: fb193d94eaac
Create Date: 2024-04-17 11:03:52.432281

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '0ba29cda6a9f'
down_revision: Union[str, None] = 'fb193d94eaac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
