"""Initial tables

Revision ID: 1f901c540024
Revises: 0ba29cda6a9f
Create Date: 2024-04-17 12:36:09.664226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f901c540024'
down_revision: Union[str, None] = '0ba29cda6a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_image_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_image_key', 'users', ['image'])
    # ### end Alembic commands ###
