"""Initial tables

Revision ID: 58c677fee32f
Revises: 8981dc63b9f1
Create Date: 2024-04-17 12:38:34.648022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c677fee32f'
down_revision: Union[str, None] = '8981dc63b9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'phone',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=26),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'phone',
        existing_type=sa.String(length=26),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
