"""Initial tables

Revision ID: 6f7c65e1c311
Revises: 3254dd909dd8
Create Date: 2024-04-26 12:54:09.655375

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6f7c65e1c311'
down_revision: Union[str, None] = '3254dd909dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
