"""Initial tables

Revision ID: 7c153ea4ccdf
Revises: 8314c1d2c169
Create Date: 2024-04-17 15:24:22.593075

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '7c153ea4ccdf'
down_revision: Union[str, None] = '8314c1d2c169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
