"""Initial tables

Revision ID: 8981dc63b9f1
Revises: 1f901c540024
Create Date: 2024-04-17 12:37:40.984884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8981dc63b9f1'
down_revision: Union[str, None] = '1f901c540024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'image',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'image',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
