"""Initial tables

Revision ID: 98924d1ffacd
Revises: fecdb21e5e00
Create Date: 2024-04-16 17:35:57.107084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98924d1ffacd'
down_revision: Union[str, None] = 'fecdb21e5e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'users', ['image'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'modified_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
