"""empty message

Revision ID: 996a1885aae6
Revises: c02eb91acdab
Create Date: 2024-05-20 14:06:33.330806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996a1885aae6'
down_revision: Union[str, None] = 'c02eb91acdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group_id', existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'group_id', existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
