"""empty message

Revision ID: bc53ae2f95c6
Revises: 996a1885aae6
Create Date: 2024-05-20 14:13:30.335265

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'bc53ae2f95c6'
down_revision: Union[str, None] = '996a1885aae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
