"""empty message

Revision ID: c4fd925836d7
Revises: bc53ae2f95c6
Create Date: 2024-05-20 14:18:54.118691

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'c4fd925836d7'
down_revision: Union[str, None] = 'bc53ae2f95c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
